import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { AuthProvider } from "@/components/context/AuthContext";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider"


export const metadata: Metadata = {
  title: "Sistema artes, plantas e flores",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
       cz-shortcut-listen="true"
        
      >
        <AuthProvider>
  <ReactQueryProvider>
    {children}
  </ReactQueryProvider>
</AuthProvider>

        <Toaster />
      </body>
    </html>
  );
}
